ngrok:
  token: your_auth_token
smtp:
  username: example@gmail.com
  password: password
  server:
    host: smtp.gmail.com
    port: 587
notification:
  active: false
  url:
    recipients: example@yopmail.com

  warnings:
    recipients: example@yopmail.com